server:
  port: 9001
  servlet:
    context-path: /bookshop/api/v1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_shop?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  type-aliases-package: com.shop.bookshop.entity
  global-config:
    db-config:
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl